### ISSUE TITLE
GroupChannel message sender metadata

### ISSUE THREAD

**Issue by RicharC293** [sendbird/Sendbird-Flutter#12]
Hi
I am accessing the metadata of a user in the BaseMessage.message property of each user but this returns an empty map, while if the query is made based on the group channel, members this if it shows me the metadata.

Note: I mean the user metadata for each post, not the channel metadata.

**Comment by intoxicated** [comment]
Hi @RicharC293 I'm afraid I understand your situation correctly. Would you please share some code snippet and what you expect to get?

**Comment by RicharC293** [comment]
I'm use this code to connect user with server and I set metadata user
https://gist.github.com/RicharC293/1cd483ceae15f37c2fbf185afdae5d52#file-connectuser-dart
In your example code 
https://github.com/sendbird/Sendbird-Flutter/blob/master/lib/screens/channel/channel_view_model.dart#L95
Load all messages in current channel
You build all messages in build content
https://github.com/sendbird/Sendbird-Flutter/blob/master/lib/screens/channel/channel_screen.dart#L205
If I try to access that metadata for example
`message.sender.metaData ['phone']`
This Map gives me empty.
But if I get the metadata from the GroupChannel for example
`currentChannel.members.map ((member) => member.metaData) .toList ()`
I get the metadata correctly.

**Comment by intoxicated** [comment]
I just tested on sample with your scenario, but it works that is I can see sender's metaData is filled with proper data. 
Here is what I did,

* create metaData on login_view_model.dart (line 28)
* send a message in a channel 
* break at line 255 or around `return UserMessageItem(..)` 
* confirm message.sender.metaData is set

**Comment by RicharC293** [comment]
Thanks, I was using an old version, I updated it to the new version and all the metadata arrives correctly.
