### ISSUE TITLE
HMS Services

### ISSUE THREAD

**Issue by RicharC293** [sendbird/Sendbird-Flutter#13]
I tried to implement HMS services with flutter package but it is not available. How long will it take to be available in the sendbird package?

**Comment by intoxicated** [comment]
What do you mean by package is not available? are you using flutter 2? if so theres possibility of dependency conflicts due to null safety. You can use `3.0.14-nullsafety` in case you need to use before we go for official release.

**Comment by RicharC293** [comment]
Sorry, I explained wrong.
I was referring to is registering the token for HMS services, push notification in devices wih HMS services, currently it allows me to register for FCM and APNS.

Here enum 

`/// Represents push token type`
`enum PushTokenType { none, fcm, apns }`

**Comment by intoxicated** [comment]
I see, it is not available on flutter yet, I do not have concrete ETA for this feature but around June/July is possibility.

**Comment by intoxicated** [comment]
HMS is added in `3.1.0-nullsafety.1` fyi
