### ISSUE TITLE
Push notification background iOS

### ISSUE THREAD

**Issue by jjsebastianfuertes** [sendbird/Sendbird-Flutter#14]
I'm not able to receive FCM notifications in the background while using an iOS device; Is there any special setting I can be missing?

**Comment by intoxicated** [comment]
Did you register right type of token and upload p12 certificate on sendbird dashboard?

**Comment by jjsebastianfuertes** [comment]
Yes, I added it to the dashboard. I receive foreground notifications, although background not. 
In the project, I have set regular notifications without sendbird and those I receive normally. any idea what can be happening?

**Comment by intoxicated** [comment]
what version are you using? I've confirmed that its working fine for latest sample. Please tell us sdk version and firebase version, and code snippet how you register token via sdk. Thanks

**Comment by jjsebastianfuertes** [comment]
sendbird_sdk: 3.0.13
firebase_core: 0.5.3
firebase_messaging: 7.0.3

Token is saved correctly although background notifications does not work. But only sendbird ones 🤔 

```
final _token = await FirebaseMessaging().getToken();
if (_sendBird.getConnectionState() ==
          sendBirdEnums.ConnectionState.closed) return;
await _sendBird.registerPushToken(
        type: PushTokenType.fcm,
        token: _token,
      );
```

**Comment by intoxicated** [comment]
Like I said, you have to register apns token for iOS

**Comment by jjsebastianfuertes** [comment]
I tried both

type: PushTokenType.fcm, and PushTokenType.apns both register well but only work in foreground;

**Comment by intoxicated** [comment]
There are things you can check:
1. Upload valid p12 certificate on sendbird dashboard
2. Register apns token (its not `FirebaseMessaging().getToken()`) for firebase_messaging v7 (prior flutter 2) you have to use https://pub.dev/packages/flutter_apns to retrieve apns token
