### ISSUE TITLE
Cannot Build on Android Device

### ISSUE THREAD

**Issue by WoogearKwon** [sendbird/Sendbird-Flutter#17]
The project could build successfully on the iOS but I got failed on the Android device with the error message below.

/Users/woogear/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-9.1.4/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java:20: error: cannot find symbol
import com.google.firebase.iid.FirebaseInstanceId;
                              ^
  symbol:   class FirebaseInstanceId
  location: package com.google.firebase.iid
/Users/woogear/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-9.1.4/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java:21: error: cannot find symbol
import com.google.firebase.iid.Metadata;
                              ^
  symbol:   class Metadata
  location: package com.google.firebase.iid
/Users/woogear/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-9.1.4/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java:152: error: cannot find symbol
                  : Metadata.getDefaultSenderId(FirebaseApp.getInstance());
                    ^
  symbol:   variable Metadata
  location: class FlutterFirebaseMessagingPlugin
/Users/woogear/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-9.1.4/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java:153: error: cannot find symbol
          FirebaseInstanceId.getInstance().deleteToken(senderId, "*");
          ^
  symbol:   variable FirebaseInstanceId
  location: class FlutterFirebaseMessagingPlugin
/Users/woogear/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-9.1.4/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java:165: error: cannot find symbol
                  : Metadata.getDefaultSenderId(FirebaseApp.getInstance());
                    ^
  symbol:   variable Metadata
  location: class FlutterFirebaseMessagingPlugin
/Users/woogear/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-9.1.4/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java:166: error: cannot find symbol
          String token = FirebaseInstanceId.getInstance().getToken(senderId, "*");
                         ^
  symbol:   variable FirebaseInstanceId
  location: class FlutterFirebaseMessagingPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_messaging:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by intoxicated** [comment]
would you update sample to latest version and try again?

**Comment by WoogearKwon** [comment]
I have tried the sample app with the firebase related code removed.
Got success after updating the sample code anyway. Thanks!
