### ISSUE TITLE
Cannot build for Android

### ISSUE THREAD

**Issue by zeffd** [sendbird/Sendbird-Flutter#18]
While building it for android, getting this error:

> Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
/Users/.../dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.6.0/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java:92: error: cannot find symbol
        () -> {
        ^
  symbol:   method metafactory(Lookup,String,MethodType,MethodType,MethodHandle,MethodType)
  location: interface LambdaMetafactory
Note: /Users/dsingh/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.6.0/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
Fatal Error: Unable to find method metafactory
':firebase_core:compileDebugJavaWithJavac'.

**Comment by jalakoo** [comment]
Hi @zeffd,  

Are you seeing this with the latest commit (479a9f4 or newer)?

**Comment by jalakoo** [comment]
Closing due to lack of response. If anyone encounters exactly this same issue, will re-open.
