### ISSUE TITLE
Group Channel Metadata

### ISSUE THREAD

**Issue by lathamios** [sendbird/Sendbird-Flutter#2]
Hi

Package is looking good! Is it possible to include the metadata of the group channel in the group channel object, similar to this change in the iOS & Android SDKs:

Android: https://github.com/sendbird/SendBird-SDK-Android/releases/tag/v3.0.158
iOS: https://github.com/sendbird/sendbird-ios-framework/releases/tag/v3.0.216

UPDATE: I think you are but from what I can see it's been commented out at present:
.pub-cache/hosted/dl.cloudsmith.io%47public%47sendbird%47sendbird-sdk-flutter%47dart%47/sendbirdsdk-3.0.4/lib/src/services/network/api_client.dart

Line 1408

Can you confirm? Thanks!

**Comment by intoxicated** [comment]
Ho @lathamios cached meta data will be released around end of this week or early next week. I am still working on that feature's test cases to make sure it works as expected.
