### ISSUE TITLE
Support for send bird calls 

### ISSUE THREAD

**Issue by luvishq** [sendbird/Sendbird-Flutter#3]
Question : When are you planning to support sendbird calls ? Also i don't see flutter docs here : https://sendbird.com/docs/chat

Can you add those ?

**Comment by intoxicated** [comment]
Not sure we have any plan to do call for flutter yet. Official docs will be updated early April :)

**Comment by asaarnak** [comment]
Are there any community plugins for sendbird calls for Flutter?
