### ISSUE TITLE
GroupChannel and User Metadata

### ISSUE THREAD

**Issue by lathamios** [sendbird/Sendbird-Flutter#7]
First of all the package is making nice progress! I have a couple of questions regarding metadata both for users and for GroupChannels

**Groupchannel**
I am running queries like so:

```
GroupChannelListQuery query = GroupChannelListQuery()
                                ..limit = 20
                                ..order = GroupChannelListOrder.latestLastMessage
                                ..includeMetaData = true;

```
But I think there's a method missing for accessing the metaData object - I can use getCachedMetaData('key') once the query is returned to get the Metadata from the cache,  shouldn't it already be included in the query object? 

**User**

When I try to get user.metaData it just returns:

```

{}

```

Even though from the logging I can see metadata for each user

**Comment by intoxicated** [comment]
Hi @lathamios 
getCachedMetaData (map) is already in BaseChannel which is accessible from GroupChannel. And for user, could you specify which method you use to get user and see empty metaData?

**Comment by lathamios** [comment]
@intoxicated Regarding the GroupChannel Metadata, yes I access it that way my question was more whether is is also accessible so:

```
groupChannel[0].metaData;

```

For the user metadata, I am trying to get it this way:

```
//result is a GroupChannel
for(var j = 0; j < result.members.length ;j++){
            List<String> meta = [];
            result.members[j].metaData.entries.forEach((element) => meta.add(element.key));

            // this statement then gives me an empty result:
            print(meta.join(',');
}

```

**Comment by intoxicated** [comment]
No we do not have property for channel. This is because metadata field is not tightly coupled with channel entity on our backend, and that's why we have getMetaData method separately on BaseChannel.

**Comment by lathamios** [comment]
Re: groupChannel metadata, great, that solution works! Any idea what's causing the user metadata issue?

**Comment by intoxicated** [comment]
would you please specify the scenario that you see empty metadata for user?

**Comment by lathamios** [comment]
Sure :
1. I do a query to get a list of groupChannels.
2. For each group channel I get then members.
3. For each member I try to get the user metadata for that member.

I get an empty result when I do this

**Comment by intoxicated** [comment]
Ok I found the issue! Thanks for the report.

**Comment by intoxicated** [comment]
Will update the SDK within this week FYI @lathamios
