### ISSUE TITLE
BadRequest on registering a push token

### ISSUE THREAD

**Issue by lathamios** [sendbird/Sendbird-Flutter#8]
Hi! Thanks for adding push notifications to the repository. I made the appropriate changes to my app, but I am not receiving push alerts on my Android phone. I think it's because of the following error I am receiving:

```

E/flutter (10209): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Instance of 'BadRequestError'
[        ] E/flutter (10209): #0      HttpClient._response (package:sendbird_sdk/services/network/http_client.dart:258:9)
[        ] E/flutter (10209): #1      HttpClient.post (package:sendbird_sdk/services/network/http_client.dart:115:12)
[        ] E/flutter (10209): <asynchronous suspension>
[        ] E/flutter (10209): #2      ApiClient.registerPushToken (package:sendbird_sdk/services/network/api_client.dart:1228:5)
[        ] E/flutter (10209): <asynchronous suspension>
[        ] E/flutter (10209): #3      ChannelListViewModel._registerTokenIfNeeded (package:nl/providers/sendbird/channel_list_view_model.dart:123:7)
[        ] E/flutter (10209): <asynchronous suspension>

```
The token is definitely being sent. I have not yet tested this on iOS

**Comment by intoxicated** [comment]
did you update your sdk to 3.0.10? I don't see this error

**Comment by intoxicated** [comment]
feel free to reopen if you still face this issue on latest sdk.

**Comment by lathamios** [comment]
Thanks, @intoxicated  after updating the SDK i am not seeing the error any more and the token is registered for the user although also not receiving the notifications currently.
